INCFLAGS += -I$(CORE_DIR) -I$(CORE_DIR)/libretro-common/include

SOURCES_CXX := \
					$(CORE_DIR)/audio_driver_libretro.cpp \
					$(CORE_DIR)/avr8.cpp \
					$(CORE_DIR)/input_driver_libretro.cpp \
					$(CORE_DIR)/SDEmulator.cpp \
					$(CORE_DIR)/uzem_libretro.cpp \
					$(CORE_DIR)/uzerom.cpp \
					$(CORE_DIR)/video_driver_libretro.cpp

